enyo.depends(
    'CroppedImage.js',
    'Illustration.js',
    'ImageButton.js',
    'IntegerSlider.js',
    'PasswordDialog.js',
    'SessionStars.js',
    'GridItem.js',
    'LevelMenuItem.js',
    'ChildItem.js',
	'QuitDialog.js'
);
