enyo.depends(
    'persistence.js',
    'persistence.store.sql.js',
    'persistence.store.websql.js',
    'persistence.sync.js',
    'persistence.migrations.js',
    'JSONH.js',
    'persistence.store.sql.compressedjson.js'
);